//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsBIMovil
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.2.0.189/bimovil_mensajes", ConfigurationName="wsBIMovil.MensajesSoap")]
    public interface MensajesSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/bimovil_mensajesX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeResponse> Envia_MensajeAsync(wsBIMovil.Envia_MensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/bimovil_mensajes_string", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_Mensaje_stringResponse> Envia_Mensaje_stringAsync(wsBIMovil.Envia_Mensaje_stringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/bimovil_mensajesXCuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeXCuentaResponse> Envia_MensajeXCuentaAsync(wsBIMovil.Envia_MensajeXCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_sinop_stringResponse> envia_mensaje_sinop_stringAsync(wsBIMovil.envia_mensaje_sinop_stringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/lista_operadores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.Lista_OperadoresResponse> Lista_OperadoresAsync(wsBIMovil.Lista_OperadoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/envia_mensaje_email", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_emailResponse> envia_mensaje_emailAsync(wsBIMovil.envia_mensaje_emailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.2.0.189/bimovil_mensajes_segcorp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_segcorpResponse> envia_mensaje_segcorpAsync(wsBIMovil.envia_mensaje_segcorpRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://10.2.0.189/bimovil_mensajesX")]
    public partial class Envia_MensajeResponseEnvia_MensajeResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_Mensaje", WrapperNamespace="http://10.2.0.189/bimovil_mensajesX", IsWrapped=true)]
    public partial class Envia_MensajeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=2)]
        public string Telefono_SMS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=3)]
        public string Operador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=4)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=5)]
        public string Numero_Transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=6)]
        public string enmascarar_desde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=7)]
        public string enmascarar_hasta;
        
        public Envia_MensajeRequest()
        {
        }
        
        public Envia_MensajeRequest(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string Numero_Transaccion, string enmascarar_desde, string enmascarar_hasta)
        {
            this.User = User;
            this.Pass = Pass;
            this.Telefono_SMS = Telefono_SMS;
            this.Operador = Operador;
            this.Mensaje_TXT = Mensaje_TXT;
            this.Numero_Transaccion = Numero_Transaccion;
            this.enmascarar_desde = enmascarar_desde;
            this.enmascarar_hasta = enmascarar_hasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_MensajeResponse", WrapperNamespace="http://10.2.0.189/bimovil_mensajesX", IsWrapped=true)]
    public partial class Envia_MensajeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesX", Order=0)]
        public wsBIMovil.Envia_MensajeResponseEnvia_MensajeResult Envia_MensajeResult;
        
        public Envia_MensajeResponse()
        {
        }
        
        public Envia_MensajeResponse(wsBIMovil.Envia_MensajeResponseEnvia_MensajeResult Envia_MensajeResult)
        {
            this.Envia_MensajeResult = Envia_MensajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_Mensaje_string", WrapperNamespace="http://10.2.0.189/bimovil_mensajes_string", IsWrapped=true)]
    public partial class Envia_Mensaje_stringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=2)]
        public string Telefono_SMS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=3)]
        public string Operador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=4)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=5)]
        public string Numero_Transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=6)]
        public string enmascarar_desde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=7)]
        public string enmascarar_hasta;
        
        public Envia_Mensaje_stringRequest()
        {
        }
        
        public Envia_Mensaje_stringRequest(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string Numero_Transaccion, string enmascarar_desde, string enmascarar_hasta)
        {
            this.User = User;
            this.Pass = Pass;
            this.Telefono_SMS = Telefono_SMS;
            this.Operador = Operador;
            this.Mensaje_TXT = Mensaje_TXT;
            this.Numero_Transaccion = Numero_Transaccion;
            this.enmascarar_desde = enmascarar_desde;
            this.enmascarar_hasta = enmascarar_hasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_Mensaje_stringResponse", WrapperNamespace="http://10.2.0.189/bimovil_mensajes_string", IsWrapped=true)]
    public partial class Envia_Mensaje_stringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_string", Order=0)]
        public string Envia_Mensaje_stringResult;
        
        public Envia_Mensaje_stringResponse()
        {
        }
        
        public Envia_Mensaje_stringResponse(string Envia_Mensaje_stringResult)
        {
            this.Envia_Mensaje_stringResult = Envia_Mensaje_stringResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://10.2.0.189/bimovil_mensajesXCuenta")]
    public partial class Envia_MensajeXCuentaResponseEnvia_MensajeXCuentaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_MensajeXCuenta", WrapperNamespace="http://10.2.0.189/bimovil_mensajesXCuenta", IsWrapped=true)]
    public partial class Envia_MensajeXCuentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=2)]
        public string Banco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=3)]
        public string Tipo_Cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=4)]
        public string Numero_Cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=5)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=6)]
        public string Numero_Transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=7)]
        public string Sistema_Origen;
        
        public Envia_MensajeXCuentaRequest()
        {
        }
        
        public Envia_MensajeXCuentaRequest(string User, string Pass, string Banco, string Tipo_Cuenta, string Numero_Cuenta, string Mensaje_TXT, string Numero_Transaccion, string Sistema_Origen)
        {
            this.User = User;
            this.Pass = Pass;
            this.Banco = Banco;
            this.Tipo_Cuenta = Tipo_Cuenta;
            this.Numero_Cuenta = Numero_Cuenta;
            this.Mensaje_TXT = Mensaje_TXT;
            this.Numero_Transaccion = Numero_Transaccion;
            this.Sistema_Origen = Sistema_Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Envia_MensajeXCuentaResponse", WrapperNamespace="http://10.2.0.189/bimovil_mensajesXCuenta", IsWrapped=true)]
    public partial class Envia_MensajeXCuentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajesXCuenta", Order=0)]
        public wsBIMovil.Envia_MensajeXCuentaResponseEnvia_MensajeXCuentaResult Envia_MensajeXCuentaResult;
        
        public Envia_MensajeXCuentaResponse()
        {
        }
        
        public Envia_MensajeXCuentaResponse(wsBIMovil.Envia_MensajeXCuentaResponseEnvia_MensajeXCuentaResult Envia_MensajeXCuentaResult)
        {
            this.Envia_MensajeXCuentaResult = Envia_MensajeXCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_sinop_string", WrapperNamespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", IsWrapped=true)]
    public partial class envia_mensaje_sinop_stringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=2)]
        public string Telefono_SMS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=3)]
        public string Pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=4)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=5)]
        public string Numero_Transaccion;
        
        public envia_mensaje_sinop_stringRequest()
        {
        }
        
        public envia_mensaje_sinop_stringRequest(string User, string Pass, string Telefono_SMS, string Pais, string Mensaje_TXT, string Numero_Transaccion)
        {
            this.User = User;
            this.Pass = Pass;
            this.Telefono_SMS = Telefono_SMS;
            this.Pais = Pais;
            this.Mensaje_TXT = Mensaje_TXT;
            this.Numero_Transaccion = Numero_Transaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_sinop_stringResponse", WrapperNamespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", IsWrapped=true)]
    public partial class envia_mensaje_sinop_stringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_envia_mensaje_sinop_string", Order=0)]
        public string envia_mensaje_sinop_stringResult;
        
        public envia_mensaje_sinop_stringResponse()
        {
        }
        
        public envia_mensaje_sinop_stringResponse(string envia_mensaje_sinop_stringResult)
        {
            this.envia_mensaje_sinop_stringResult = envia_mensaje_sinop_stringResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://10.2.0.189/lista_operadores")]
    public partial class Lista_OperadoresResponseLista_OperadoresResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lista_Operadores", WrapperNamespace="http://10.2.0.189/lista_operadores", IsWrapped=true)]
    public partial class Lista_OperadoresRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/lista_operadores", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/lista_operadores", Order=1)]
        public string Pass;
        
        public Lista_OperadoresRequest()
        {
        }
        
        public Lista_OperadoresRequest(string User, string Pass)
        {
            this.User = User;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lista_OperadoresResponse", WrapperNamespace="http://10.2.0.189/lista_operadores", IsWrapped=true)]
    public partial class Lista_OperadoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/lista_operadores", Order=0)]
        public wsBIMovil.Lista_OperadoresResponseLista_OperadoresResult Lista_OperadoresResult;
        
        public Lista_OperadoresResponse()
        {
        }
        
        public Lista_OperadoresResponse(wsBIMovil.Lista_OperadoresResponseLista_OperadoresResult Lista_OperadoresResult)
        {
            this.Lista_OperadoresResult = Lista_OperadoresResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://10.2.0.189/envia_mensaje_email")]
    public partial class envia_mensaje_emailResponseEnvia_mensaje_emailResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_email", WrapperNamespace="http://10.2.0.189/envia_mensaje_email", IsWrapped=true)]
    public partial class envia_mensaje_emailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=2)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=3)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=4)]
        public string Numero_Transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=5)]
        public string instancia_aws;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=6)]
        public string pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=7)]
        public string enmascarar_desde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=8)]
        public string enmascarar_hasta;
        
        public envia_mensaje_emailRequest()
        {
        }
        
        public envia_mensaje_emailRequest(string User, string Pass, string email, string Mensaje_TXT, string Numero_Transaccion, string instancia_aws, string pais, string enmascarar_desde, string enmascarar_hasta)
        {
            this.User = User;
            this.Pass = Pass;
            this.email = email;
            this.Mensaje_TXT = Mensaje_TXT;
            this.Numero_Transaccion = Numero_Transaccion;
            this.instancia_aws = instancia_aws;
            this.pais = pais;
            this.enmascarar_desde = enmascarar_desde;
            this.enmascarar_hasta = enmascarar_hasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_emailResponse", WrapperNamespace="http://10.2.0.189/envia_mensaje_email", IsWrapped=true)]
    public partial class envia_mensaje_emailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/envia_mensaje_email", Order=0)]
        public wsBIMovil.envia_mensaje_emailResponseEnvia_mensaje_emailResult envia_mensaje_emailResult;
        
        public envia_mensaje_emailResponse()
        {
        }
        
        public envia_mensaje_emailResponse(wsBIMovil.envia_mensaje_emailResponseEnvia_mensaje_emailResult envia_mensaje_emailResult)
        {
            this.envia_mensaje_emailResult = envia_mensaje_emailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_segcorp", WrapperNamespace="http://10.2.0.189/bimovil_mensajes_segcorp", IsWrapped=true)]
    public partial class envia_mensaje_segcorpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=1)]
        public string Pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=2)]
        public string Telefono_SMS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=3)]
        public string Operador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=4)]
        public string Mensaje_TXT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=5)]
        public string otp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=6)]
        public string Numero_Transaccion;
        
        public envia_mensaje_segcorpRequest()
        {
        }
        
        public envia_mensaje_segcorpRequest(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string otp, string Numero_Transaccion)
        {
            this.User = User;
            this.Pass = Pass;
            this.Telefono_SMS = Telefono_SMS;
            this.Operador = Operador;
            this.Mensaje_TXT = Mensaje_TXT;
            this.otp = otp;
            this.Numero_Transaccion = Numero_Transaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="envia_mensaje_segcorpResponse", WrapperNamespace="http://10.2.0.189/bimovil_mensajes_segcorp", IsWrapped=true)]
    public partial class envia_mensaje_segcorpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.2.0.189/bimovil_mensajes_segcorp", Order=0)]
        public string envia_mensaje_segcorpResult;
        
        public envia_mensaje_segcorpResponse()
        {
        }
        
        public envia_mensaje_segcorpResponse(string envia_mensaje_segcorpResult)
        {
            this.envia_mensaje_segcorpResult = envia_mensaje_segcorpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MensajesSoapChannel : wsBIMovil.MensajesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MensajesSoapClient : System.ServiceModel.ClientBase<wsBIMovil.MensajesSoap>, wsBIMovil.MensajesSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MensajesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MensajesSoapClient.GetBindingForEndpoint(endpointConfiguration), MensajesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MensajesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MensajesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MensajesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeResponse> wsBIMovil.MensajesSoap.Envia_MensajeAsync(wsBIMovil.Envia_MensajeRequest request)
        {
            return base.Channel.Envia_MensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeResponse> Envia_MensajeAsync(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string Numero_Transaccion, string enmascarar_desde, string enmascarar_hasta)
        {
            wsBIMovil.Envia_MensajeRequest inValue = new wsBIMovil.Envia_MensajeRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.Telefono_SMS = Telefono_SMS;
            inValue.Operador = Operador;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.Numero_Transaccion = Numero_Transaccion;
            inValue.enmascarar_desde = enmascarar_desde;
            inValue.enmascarar_hasta = enmascarar_hasta;
            return ((wsBIMovil.MensajesSoap)(this)).Envia_MensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_Mensaje_stringResponse> wsBIMovil.MensajesSoap.Envia_Mensaje_stringAsync(wsBIMovil.Envia_Mensaje_stringRequest request)
        {
            return base.Channel.Envia_Mensaje_stringAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.Envia_Mensaje_stringResponse> Envia_Mensaje_stringAsync(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string Numero_Transaccion, string enmascarar_desde, string enmascarar_hasta)
        {
            wsBIMovil.Envia_Mensaje_stringRequest inValue = new wsBIMovil.Envia_Mensaje_stringRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.Telefono_SMS = Telefono_SMS;
            inValue.Operador = Operador;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.Numero_Transaccion = Numero_Transaccion;
            inValue.enmascarar_desde = enmascarar_desde;
            inValue.enmascarar_hasta = enmascarar_hasta;
            return ((wsBIMovil.MensajesSoap)(this)).Envia_Mensaje_stringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeXCuentaResponse> wsBIMovil.MensajesSoap.Envia_MensajeXCuentaAsync(wsBIMovil.Envia_MensajeXCuentaRequest request)
        {
            return base.Channel.Envia_MensajeXCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.Envia_MensajeXCuentaResponse> Envia_MensajeXCuentaAsync(string User, string Pass, string Banco, string Tipo_Cuenta, string Numero_Cuenta, string Mensaje_TXT, string Numero_Transaccion, string Sistema_Origen)
        {
            wsBIMovil.Envia_MensajeXCuentaRequest inValue = new wsBIMovil.Envia_MensajeXCuentaRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.Banco = Banco;
            inValue.Tipo_Cuenta = Tipo_Cuenta;
            inValue.Numero_Cuenta = Numero_Cuenta;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.Numero_Transaccion = Numero_Transaccion;
            inValue.Sistema_Origen = Sistema_Origen;
            return ((wsBIMovil.MensajesSoap)(this)).Envia_MensajeXCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_sinop_stringResponse> wsBIMovil.MensajesSoap.envia_mensaje_sinop_stringAsync(wsBIMovil.envia_mensaje_sinop_stringRequest request)
        {
            return base.Channel.envia_mensaje_sinop_stringAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_sinop_stringResponse> envia_mensaje_sinop_stringAsync(string User, string Pass, string Telefono_SMS, string Pais, string Mensaje_TXT, string Numero_Transaccion)
        {
            wsBIMovil.envia_mensaje_sinop_stringRequest inValue = new wsBIMovil.envia_mensaje_sinop_stringRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.Telefono_SMS = Telefono_SMS;
            inValue.Pais = Pais;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.Numero_Transaccion = Numero_Transaccion;
            return ((wsBIMovil.MensajesSoap)(this)).envia_mensaje_sinop_stringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.Lista_OperadoresResponse> wsBIMovil.MensajesSoap.Lista_OperadoresAsync(wsBIMovil.Lista_OperadoresRequest request)
        {
            return base.Channel.Lista_OperadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.Lista_OperadoresResponse> Lista_OperadoresAsync(string User, string Pass)
        {
            wsBIMovil.Lista_OperadoresRequest inValue = new wsBIMovil.Lista_OperadoresRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            return ((wsBIMovil.MensajesSoap)(this)).Lista_OperadoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_emailResponse> wsBIMovil.MensajesSoap.envia_mensaje_emailAsync(wsBIMovil.envia_mensaje_emailRequest request)
        {
            return base.Channel.envia_mensaje_emailAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_emailResponse> envia_mensaje_emailAsync(string User, string Pass, string email, string Mensaje_TXT, string Numero_Transaccion, string instancia_aws, string pais, string enmascarar_desde, string enmascarar_hasta)
        {
            wsBIMovil.envia_mensaje_emailRequest inValue = new wsBIMovil.envia_mensaje_emailRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.email = email;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.Numero_Transaccion = Numero_Transaccion;
            inValue.instancia_aws = instancia_aws;
            inValue.pais = pais;
            inValue.enmascarar_desde = enmascarar_desde;
            inValue.enmascarar_hasta = enmascarar_hasta;
            return ((wsBIMovil.MensajesSoap)(this)).envia_mensaje_emailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_segcorpResponse> wsBIMovil.MensajesSoap.envia_mensaje_segcorpAsync(wsBIMovil.envia_mensaje_segcorpRequest request)
        {
            return base.Channel.envia_mensaje_segcorpAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsBIMovil.envia_mensaje_segcorpResponse> envia_mensaje_segcorpAsync(string User, string Pass, string Telefono_SMS, string Operador, string Mensaje_TXT, string otp, string Numero_Transaccion)
        {
            wsBIMovil.envia_mensaje_segcorpRequest inValue = new wsBIMovil.envia_mensaje_segcorpRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            inValue.Telefono_SMS = Telefono_SMS;
            inValue.Operador = Operador;
            inValue.Mensaje_TXT = Mensaje_TXT;
            inValue.otp = otp;
            inValue.Numero_Transaccion = Numero_Transaccion;
            return ((wsBIMovil.MensajesSoap)(this)).envia_mensaje_segcorpAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MensajesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MensajesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MensajesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://bimoviladmqa.bi.com.gt/bimovil_mensajes/mensajes.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MensajesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://bimoviladmqa.bi.com.gt/bimovil_mensajes/mensajes.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MensajesSoap,
            
            MensajesSoap12,
        }
    }
}
